### ISSUE TITLE
SSL self-signed

### ISSUE THREAD

**Issue by lukyrys** [php-mail-client/Client#6]
Cannot connect to IMAP server: Certificate failure for server.cz: Self-signed certificate or untrusted authority: C=US, S=NY, L=New York, O=Courier Mail Server, OU=Automatically-generated IMAP SSL key, CN=server.cz, E=postmaster@example.com 

settings on imapdriver constructor - port 143 , ssl FALSE.
If this set to true 

greeny\MailLibrary\DriverException
Cannot connect to IMAP server: TLS/SSL failure for server.cz: Invalid token, probably not an SSL server

fix for ssl false option:

ImapDriver.php:64
added /novalidate-cert
$ssl = $ssl ? '/ssl' : '/novalidate-cert';

**Comment by greeny** [comment]
Thanks for bug report :)
